# Generated by Django 3.0 on 2020-02-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField()),
                ('course_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('no_of_sections', models.IntegerField()),
                ('no_of_lecture', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Fid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('room_no', models.IntegerField()),
                ('campus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('enrollment_no', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=40)),
                ('course', models.CharField(choices=[('B.tech', 'B.tech'), ('MBA', 'MBA'), ('M.tech', 'M.tech'), ('BBA', 'BBA')], max_length=6)),
                ('programme', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('batch', models.IntegerField()),
                ('password', models.CharField(max_length=256)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('section_id', models.IntegerField(primary_key=True, serialize=False)),
                ('section_no', models.IntegerField()),
                ('no_of_intake', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Courses')),
                ('faculty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Sections')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Courses')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Sections')),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Students')),
            ],
        ),
        migrations.CreateModel(
            name='attendace_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attend', models.BooleanField()),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Sections')),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Students')),
            ],
        ),
    ]
